# Generated by Django 3.1.6 on 2021-03-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BITS_Assist', '0004_downvote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='of_question',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='of_question',
        ),
        migrations.AddField(
            model_name='downvote',
            name='of_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='BITS_Assist.answers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upvote',
            name='of_answer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='BITS_Assist.answers'),
            preserve_default=False,
        ),
    ]
