# Generated by Django 3.1.6 on 2021-03-21 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BITS_Assist', '0005_auto_20210315_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='of_answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='downvote',
        ),
        migrations.DeleteModel(
            name='upvote',
        ),
    ]
