# Generated by Django 3.1.6 on 2021-03-21 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BITS_Assist', '0006_auto_20210321_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
